defaults: &defaults
  googleclientid: {GOOGLE_CLIENT_ID}
  googleclientsecret: {GOOGLE_CLIENT_SECRET}
  apikey: {API_KEY}
  almaurl: https://api-na.hosted.exlibrisgroup.com/almaws/v1
  paypalurl: https://api.sandbox.paypal.com/v1
  paypayclientid: {PAYPAL_CLIENT_ID}
  paypalsecret: {PAYPAL_SECRET}
  pdsurl: {PDS URL}
  amazonaccesskey: {AMAZON_ACCESS_KEY}
  amazonsecretkey: {AMAZON_SECRET_KEY}
  institution: {Alma Institution}
  domain: {AWS Cloud Search domain}
  amazonscratchbucket: {AWS S3 scratch bucket}
  amazonaccesskey: {AWS access key for scratch bucket}
  amazonsecretkey: {AWS secret key for scratch bucket}
  oaiset: {OAI set}
  alma: {Alma instance name}
  sword_user: {SWORD user name}
  sword_pass: {SWORD password}  
  root_url: {root URL of the application}
  alma_auth_secret: {auth secret for Alma authentication}

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults